/// Enum representing the different roles in a conversation with the OpenAI API.
enum Role: String, Codable {
	/// The `user` role represents inputs provided by the user.
	case user
	/// The `assistant` role represents the responses generated by the OpenAI model.
	case assistant
	/// The `system` role represents mainly error messages thrown by the app.
	case system
}
